version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: srcs_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: srcs_wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: srcs_nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_network
    restart: always

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wp_network:

